FROM node:20-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY prisma ./prisma
#or you can generate it later also like when migrating schema to db
RUN npx prisma generate

# Copy the rest of the project
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
