FROM oven/bun:1-slim

WORKDIR /app

COPY package.json ./

RUN bun install

COPY prisma ./prisma
#or you can generate it later also like when migrating schema to db
RUN bunx prisma generate

# Copy the rest of the project
COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"]
