FROM node:20

WORKDIR /app

# Copy only package.json first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy Prisma schema only so we can generate client
COPY prisma ./prisma
RUN npx prisma generate

# Copy the rest of the project
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
