import type { Metadata } from "next";
// Import fonts normally if you want, but don't use their `.variable` in body class directly if unstable
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Montserrat } from "next/font/google";
import AuthProvider from "@/AuthProvider";

export const metadata: Metadata = {
  title: "T3 Chat",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
        className={`${montserrat.variable} antialiased text-foreground min-h-screen bg-[radial-gradient(ellipse_at_center,var(--background)_20%,oklch(0.235_0.017_290)_100%)]`}
      >
        <ThemeProvider>
           <AuthProvider>
             {children}
           </AuthProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
